image: python:latest

variables:
  NOOP: ci

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 ./

test:
  stage: Test
  script:
  - python manage.py test --settings gradify.settings.ci

