image: python:latest

before_script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

cache:
  paths:
  - ~/.cache/pip/

stages:
  - Static Analysis
  - Test
  - Security Audit
  - Build
  - Deploy

flake8:
  stage: Static Analysis
  script:
  - flake8

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint --ignore-patterns=.git,core/migrations,users/migrations,manage ./*.py

bandit:
  stage: Security Audit
  allow_failure: true
  script:
    - bandit -s B105 -r ./core ./gradify ./users

unit_test:
  image: python:latest
  stage: Test
  script:
  - coverage run --omit="core/migrations/*","users/migrations/*","manage.py","core/tests/*" --source="." manage.py test --settings gradify.settings.ci
  - coverage report

deploy_heroku:
  stage: Deploy
  script:
    - git remote add heroku https://heroku:$HEROKU-API-KEY@git.heroku.com/gradify-app.git
    - git push heroku master
  environment:
    name: production
    url: https://gradify-app.herokuapp.com/
#  only:
#    - master

