image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

stages:
  - Static Analysis
  - Test
  - Security Audit

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 --exclude=.git,core/migrations ./

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint --ignore-patterns=.git,core/migrations,manage ./*.py

bandit:
  stage: Security Audit
  allow_failure: true
  script:
    - bandit -r ./core ./gradify

unit_test:
  stage: Test
  script:
  - coverage run --omit="core/migrations/*","manage.py","core/tests/*" --source="." manage.py test --settings gradify.settings.ci
  - coverage report

