# Generated by Django 2.2.1 on 2019-06-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=750)),
                ('ownerId', models.CharField(max_length=254)),
                ('enrollmentCode', models.CharField(max_length=64)),
                ('section', models.CharField(blank=True, max_length=2800)),
                ('descriptionHeading', models.CharField(blank=True, max_length=3600)),
                ('description', models.TextField(blank=True, max_length=30000)),
                ('room', models.CharField(blank=True, max_length=650)),
                ('alternateLink', models.CharField(blank=True, max_length=650)),
                ('startDate', models.DateTimeField(blank=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('courseState', models.CharField(choices=[('U', 'Unspecified'), ('A', 'Active'), ('R', 'Archived'), ('S', 'Suspended')], default='U', max_length=1)),
            ],
        ),
    ]
