# Generated by Django 2.2.1 on 2019-07-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='googleId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
