# Generated by Django 2.2.1 on 2019-06-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomId', models.CharField(max_length=750, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=750)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=750)),
                ('description', models.TextField(blank=True, max_length=30000)),
                ('max_points', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('U', 'Unspecified'), ('P', 'Published'), ('D', 'Draft'), ('X', 'Deleted')], default='U', max_length=1)),
                ('type', models.CharField(choices=[('U', 'Unspecified'), ('Q', 'Quiz'), ('T', 'Test'), ('W', 'Worksheet'), ('F', 'Final')], default='U', max_length=1)),
                ('source', models.CharField(choices=[('U', 'Unspecified'), ('C', 'Google Classroom'), ('G', 'Gradify')], default='U', max_length=1)),
                ('classrooomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Classroom')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
                ('creatorUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late', models.BooleanField(default=False)),
                ('draftGrade', models.FloatField(blank=True)),
                ('assignedGrade', models.FloatField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('U', 'Unspecified'), ('N', 'New'), ('C', 'Created'), ('T', 'Turned In'), ('R', 'Returned'), ('S', 'Reclaimed by Student')], default='U', max_length=1)),
                ('classroomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Classroom')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
                ('courseworkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CourseWork')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
