# Generated by Django 2.2.1 on 2019-07-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190703_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
