# Generated by Django 2.2.1 on 2019-07-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_googleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='googleId',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
