# Generated by Django 2.2.1 on 2019-06-23 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_coursework_studentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coursework',
            old_name='classrooomId',
            new_name='classrooom',
        ),
        migrations.RenameField(
            model_name='coursework',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursework',
            old_name='creatorUserId',
            new_name='creatorUser',
        ),
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='courseworkId',
            new_name='coursework',
        ),
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='classroomId',
        ),
        migrations.AddField(
            model_name='coursework',
            name='dueDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
