# Generated by Django 2.2.1 on 2019-07-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursework_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='workType',
            field=models.CharField(choices=[('U', 'Unspecified'), ('Q', 'Quiz'), ('T', 'Test'), ('W', 'Worksheet'), ('F', 'Final'), ('A', 'Assignment')], default='U', max_length=1),
        ),
    ]
