# Generated by Django 2.2.1 on 2019-07-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190705_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='max_points',
            new_name='maxPoints',
        ),
    ]
