# Generated by Django 2.2.1 on 2019-06-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190622_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='classrooom',
        ),
    ]
