# Generated by Django 2.2.1 on 2019-07-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190705_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='dueDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
