# Generated by Django 2.2.1 on 2019-06-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_coursework_classrooom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='creatorUser',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='course',
        ),
    ]
