# Generated by Django 2.2.1 on 2019-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190705_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
