# Generated by Django 2.2.1 on 2019-07-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190705_2247'),
        ('core', '0003_delete_classroom'),
    ]

    operations = [
    ]
