# Generated by Django 2.2.1 on 2019-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20190706_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='workType',
            new_name='courseWorkType',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='alternateLink',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
