# Generated by Django 2.2.1 on 2019-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190706_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='gcSubmissionId',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
