# Generated by Django 2.2.1 on 2019-07-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentsubmission_gcsubmissionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='assignedGrade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='draftGrade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
