# Generated by Django 2.2.2 on 2019-07-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190706_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='courseWorkType',
            new_name='workType',
        ),
    ]
