# Generated by Django 2.2.2 on 2019-07-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190707_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='courseWorkType',
            field=models.CharField(choices=[('U', 'Unspecified'), ('A', 'Assignment'), ('S', 'Short Answer Question'), ('M', 'Multiple Choice Question')], default='U', max_length=1),
        ),
    ]
